name : checks

on:
  push:
    branches:
      - main

jobs: 
  test-lint:
    name: test and lint
    runs-on: ubuntu-latest


    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: test
        run: docker compose --rm app sh -c "python manage.py test"  

      - name: lint
        run: docker compose --rm app sh -c "flake8"  





    

